spring:
  datasource:
    url: jdbc:h2:tcp://localhost/file:D:/Tool/h2_db/querydsl
    username: sa
    password: 1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comment: true #querydsl의 JPQL 확인 가능

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace